# -*- coding: utf-8 -*-
"""Проект зимние тренды

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Sjrm62U9phWxUV0SVma3Tz3zfOA8ZZt

# Анализ модных трендов зимы

### **А. Загрузка и первичный обзор**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Загрузка данных
df = pd.read_csv("Winter_Fashion_Trends_Dataset.csv")

#Первые строки
df.head()

#Последние строки
df.tail()

#Общая информация о датасете
df.info()

#Проверка типов данных
df.dtypes

"""Типы данных корректны

### **В. Обработка данных**
"""

#Поиск пропусков
df.isnull().sum()

numeric_cols = ['Price(USD)', 'Popularity_Score', 'Customer_Rating']
categorical_cols = ['Brand', 'Category', 'Color', 'Material', 'Style', 'Gender', 'Season', 'Trend_Status']

#Заполнение числовых столбцов медианой
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

#Заполнение категориальных столбцов модой
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Поиск дубликатов
duplicates = df.duplicated().sum()
print(f"Количество дубликатов: {duplicates}")

#Поиск и удаление выбросов
from scipy.stats import zscore
z_scores = np.abs(zscore(df[numeric_cols]))
df = df[(z_scores < 3).all(axis=1)]

"""### **С. Графики**"""

plt.figure()
plt.hist(df['Price(USD)'], bins=25)
plt.title("Распределение цен")
plt.show()

df['Category'].value_counts().plot(kind='bar')
plt.title("Количество товаров по категориям")
plt.show()

df.groupby('Category')['Price(USD)'].mean().plot(kind='bar')
plt.title("Средняя цена по категориям")
plt.show()

sns.boxplot(x='Category', y='Price(USD)', data=df)
plt.title("Распределение цен по категориям")
plt.xticks(rotation=45)
plt.show()

sns.heatmap(df[numeric_cols].corr(), annot=True)
plt.title("Корреляция")
plt.show()

"""### **D. Группировки и агрегации**"""

#Таблица со средними ценами
df.groupby('Season')['Price(USD)'].mean()

#Средние баллы популярности
df.groupby('Trend_Status')['Popularity_Score'].mean()

#Средние рейтинги по категориям и полу
pd.pivot_table(
    df,
    values='Customer_Rating',
    index='Category',
    columns='Gender',
    aggfunc='mean'
)